# Generated by Django 5.2.3 on 2025-06-28 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('target', '0001_initial'),
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word.wordcategory')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='target.learningtarget')),
            ],
        ),
        migrations.CreateModel(
            name='DailyMissionWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daily_mission.dailymission')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word.word')),
            ],
            options={
                'unique_together': {('daily_mission', 'word')},
            },
        ),
    ]
