# Generated by Django 5.2.3 on 2025-06-29 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_mission', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailymission',
            name='category',
        ),
    ]
