scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9200']

  - job_name: 'flower'
    static_configs:
      - targets: ['flower:5555']

  - job_name: 'celery_exporter'
    static_configs:
      - targets: ['celery_exporter:9808']
