# Generated by Django 5.2.3 on 2025-06-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_mission', '0002_remove_dailymission_category'),
        ('word', '0002_learnedword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='category',
            field=models.CharField(choices=[('SHORT', 'short'), ('MEDIUM', 'short'), ('LONG', 'long')], default='SHORT', max_length=20),
        ),
        migrations.DeleteModel(
            name='WordCategory',
        ),
    ]
