name: CD - Deploy on main

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Debug SSH key
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" | ssh-add -

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Debug SSH key
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" | ssh-add -

      - name: Run remote commands
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
            cd /home/mobinuser/english_learning &&
            git pull origin main &&
            docker compose restart
          "
